gcc ${1}c-destroy-session.c -o ${1}c-destroy-session.cgi
gcc ${1}c-env.c -o ${1}c-env.cgi
gcc ${1}c-general-request-echo.c -o ${1}c-general-request-echo.cgi
gcc ${1}c-get-echo.c -o ${1}c-get-echo.cgi
gcc ${1}c-hello-html.c -o ${1}c-hello-html.cgi
gcc ${1}c-hello-json.c -o ${1}c-hello-json.cgi
gcc ${1}c-post-echo.c -o ${1}c-post-echo.cgi
gcc ${1}c-sessions-1.c -o ${1}c-sessions-1.cgi
gcc ${1}c-sessions-2.c -o ${1}c-sessions-2.cgi