gcc c-destroy-session.c -o c-destroy-session.cgi
gcc c-env.c -o c-env.cgi
gcc c-general-request-echo.c -o c-general-request-echo.cgi
gcc c-get-echo.c -o c-get-echo.cgi
gcc c-hello-html-world.c -o c-hello-html-world.cgi
gcc c-hello-json-world.c -o c-hello-json-world.cgi
gcc c-post-echo.c -o c-post-echo.cgi
gcc c-sessions-1.c -o c-sessions-1.cgi
gcc c-sessions-2.c -o c-sessions-2.cgi