go build -o ${1}go-destroy-session.cgi ${1}go-destroy-session.go
go build -o ${1}go-env.cgi ${1}go-env.go
go build -o ${1}go-general-request-echo.cgi ${1}go-general-request-echo.go
go build -o ${1}go-get-echo.cgi ${1}go-get-echo.go
go build -o ${1}go-hello-html.cgi ${1}go-hello-html.go
go build -o ${1}go-hello-json.cgi ${1}go-hello-json.go
go build -o ${1}go-post-echo.cgi ${1}go-post-echo.go
go build -o ${1}go-sessions-1.cgi ${1}go-sessions-1.go
go build -o ${1}go-sessions-2.cgi ${1}go-sessions-2.go