# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: 	ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy Website
        uses: appleboy/ssh-action@v0.1.4
        env:
          SITE_PATH: ${{secrets.SITE_PATH}}
          WWW_PATH: ${{secrets.WWW_PATH}}
          CGI_PATH: ${{secrets.CGI_PATH}}
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          envs: SITE_PATH, WWW_PATH, CGI_PATH
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            cd ${SITE_PATH} # open site path
            git init        # initialize git
            git remote add origin git@github.com:DarrenWu42/cse135webserver.git # add repo, just in case line
            git pull origin main                   # pull from repo
            sudo chgrp -R sudo ${SITE_PATH}        # change group to sudo
            sudo chmod -R a=r,ug+w,a+X ${WWW_PATH} # change to correct permissions
            
            # allow sh files to be executable, run sh files, then disallow sh files to be executable
            sudo chmod ug+x ${CGI_PATH}*.sh        # allow all sh files to be executable
            sudo ${CGI_PATH}compile-c.sh $CGI_PATH # compile all c files to cgi files
            sudo chmod ug-x ${CGI_PATH}*.sh        # disallow all sh files to be executable
            
            # set permissions for exectuable files cgi, php, pl
            sudo chmod a+x ${CGI_PATH}*.cgi # allow execute only on .cgi files by all
            sudo chmod a+x ${CGI_PATH}*.pl  # allow execute only on .pl files by all
