# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: 	ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy Website
        uses: appleboy/ssh-action@v0.1.4
        env:
          SITE_PATH: ${{secrets.SITE_PATH}}
          WWW_PATH: ${{secrets.WWW_PATH}}
          CGI_PATH: ${{secrets.GCI_PATH}}
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          envs: SITE_PATH, WWW_PATH, CGI_PATH
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            cd $SITE_PATH # open site path
            git init                  # initialize git
            git remote add origin git@github.com:DarrenWu42/cse135webserver.git # add repo
            git pull origin main      # pull from repo
            sudo chgrp -R sudo $SITE_PATH        # change group to sudo
            sudo chmod -R a=r,ug+w,a+X $www_PATH # change to correct settings
            sudo chmod -R a+x $CGI_PATH          # allow cgi bin to be executable
