# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: 	ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy Website
        uses: appleboy/ssh-action@v0.1.4
        env:
          SITE_PATH: ${{secrets.SITE_PATH}}
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            cd /var/www/darrenwu.xyz/ # open site path
            git init                  # initialize git
            git remote add origin git@github.com:DarrenWu42/cse135webserver.git # add repo
            git pull origin main      # pull from repo
            cd ..                     # go up one level
            sudo chgrp -R sudo darrenwu.xyz/ # change group to sudo
